name: update

on:
  schedule:
    - cron: '0 15 * * *'

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: git fetch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout main
          git fetch
          git pull origin main
      
      - name: update
        run: node scripts/update.js

      - name: commit database.json
        run: |
          git add .
          git commit -m 'update database.json'
          git push 'https://${{ secrets.GITHUB_TOKEN }}@github.com/taikowiki/taiko-song-database'

      - name: make history
        run: node scripts/history.js 
      
      - name: commit history
        run: |
          git add .
          git commit -m 'update history'
          git push 'https://${{ secrets.GITHUB_TOKEN }}@github.com/taikowiki/taiko-song-database'
